<?php
require_once 'core/init.php';

if(Session::exists('success')){
    echo Session::flash('success');
}

$user = new User();
if($user->isLoggedIn()){
?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Agri world</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link rel="stylesheet" href="css/styles.css" />
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link href="css/font-awesome.min.css" rel="stylesheet" />
  </head>
  <body >
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.php">Agri-World</a>
        </div>
        <div class="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="index.php">View page</a></li>
            <li><a href="profile.php?user=<?php echo escape($user->data()->username);?>">Hello! <b><?php echo escape($user->data()->username);?></b></a></li>
            <li><a href="logout.php">
              <span class="glyphicon glyphicon-log-in"></span>
              Logout
            </a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
</nav>
<br><br>
<div class="container-fluid">
      <br>
      <div class="row row-offcanvas row-offcanvas-left">
        <p class="visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
          </p>
         <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
           
            <ul id="side-bar" class="nav nav-sidebar">
              <li class="active"><a href="#">
                <span class="glyphicon glyphicon-tasks"></span>
                Overview
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-edit"></span>
                Edits
              </a></li>
              <li><a href="addproduct.php">
                <span class="glyphicon glyphicon-pencil"></span>
                Add New Products
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-shopping-cart"></span>
                Cart
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-print"></span>
                Reports
              </a></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li><a href="">Nav item again</a></li>
              <li><a href="">One more nav</a></li>
              <li><a href="">Another nav item</a></li>
            </ul>
          
        </div><!--/span-->
        
        <div class="col-sm-9 col-md-10 main">
          <!--toggle sidebar button-->
          
            <header>
              <h4 class="page_title">Dashboard</h4>
            </header>
         <?php if($user->hasPermission('admin')){?>   
            <div class="content-inner">
              <div class="form-wrapper">
                <div class="row">
                  <h5> <a class="btn" href="admin.php?type=user">User privileges</a></h5>
            <?php if(isset($_GET['type']) && !empty($_GET['type'])){?>
                  <table class="table table-bordered">
                      <thead>
                          <tr>
                              <th>Name</th>
                              <th>Email Address</th>
                              <th>Payment Date</th>
                              <th>Status</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
      <?php $list = DB::getInstance()->query("SELECT * FROM users");
            if(!$list->count()){
                echo 'There is no user to Activate or diactivate';
            }else{
                foreach ($list->results() as $name){?>
                      <?php
                        if($name->user_approved == '1'){
                            $state = "active";
                        }else{
                          $state = "success";
                        }
                      ?>

                      <tr class="<?php echo $state;?>">
                        <?php if(!$name->is_admin == '1'){?>
                        <td><?php echo $name->username ?></td>
                        <td><?php echo $name->email ?></td>
                        <td><?php echo $name->phone ?></td>
                        <td><?php
                          if($name->user_approved == '1'){        
                              echo "<a class='btn btn-sm' href='activated_or_die.php?u_id=$name->id&type=$name->user_approved'>activate</a>";
                          }else{
                              echo "<a class='btn btn-sm' href='activated_or_die.php?u_id=$name->id&type=$name->user_approved'>Deactivate</a>";
                          }
                          echo '</td><td><button type="button"  class="btn btn-green btn-sm" data-toggle="modal" data-target="#edit"><i class="fa fa-edit fa-1x"></i></button>
                          <button type="button" class="btn btn-red btn-sm" data-toggle="modal" data-target="#delete"><i class="fa fa-remove fa-1x"></i></button>';
                          } 
                          ?>

                        </td>
                      </tr>
                     <?php 
                       }
                     }
                   ?>
                      </tbody>
                  </table>
            <?php }?>
                </div>
            </div>
          </div>
      <?php }?>

<style type="text/css">
.btn-green{
  background-color: #1abc9c;
}

.btn-red{
  background-color: #9b59b6;
}
</style>
        <!-- Trigger the modal with a button -->


<!-- Modal -->
<div id="delete" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Yes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

            <div class="content-inner">
              <div class="form-wrapper">
                <form>
                  <div class="row form-group">
                    <label class="sr-only">Title</label>
                    <div class="col-md-3">
                      <span class="">Title 1</span>
                      <input type="text" class="form-control" id="titles" placeholder="Article..1">
                    </div>
                    <div class="col-md-3">
                      <span class="">Title 2</span>
                      <input type="text" class="form-control" id="titles" placeholder="Article..2">
                    </div>
                    <div class="col-md-3">
                      <span class="">Title 3</span>
                      <input type="text" class="form-control" id="titles" placeholder="Article..3">
                    </div>
                  </div>
                  
                   <div class="clearfix">
                    <button type="submit" class="btn btn-primary">Publish</button>
                   </div>
                </form>
              </div>
            </div>
            
            
      </div><!--/row-->
	</div>
</div><!--/.container-->

<div class="footer-bottom-area">
  <div class="container">
            <div class="row">
                <div class="pull-right">
                    <div class="copyright">
                        <p>&copy; 2015 4it All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">Thusitha Thiyushan</a></p>
                    </div>
                </div>
            </div>
        </div>
</div>

    <!--scripts loaded here-->
    
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    
    <script src="js/scripts.js"></script>
  </body>
</html>
<?php
}else{
  Redirect::to('404.php');
}
?>