<?php
require_once 'core/init.php';

if(Session::exists('success')){
    echo Session::flash('success');
}

$user = new User();
if($user->isLoggedIn()){
?>

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Agri world</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
    <link rel="stylesheet" href="css/styles.css" />
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link href="css/font-awesome.min.css" rel="stylesheet" />
  </head>
  <body >
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.php">Agri-World</a>
        </div>
        <div class="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="index.php">View page</a></li>
            <li><a href="profile.php?user=<?php echo escape($user->data()->username);?>">Hello! <b><?php echo escape($user->data()->username);?></b></a></li>
            <li><a href="logout.php">
              <span class="glyphicon glyphicon-log-in"></span>
              Logout
            </a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
</nav>
<br><br>
<div class="container-fluid">
      <br>
      <div class="row row-offcanvas row-offcanvas-left">
        <p class="visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
          </p>
         <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
           
            <ul id="side-bar" class="nav nav-sidebar">
              <li class="active"><a href="#">
                <span class="glyphicon glyphicon-tasks"></span>
                Overview
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-edit"></span>
                Edits
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-pencil"></span>
                Add New Products
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-shopping-cart"></span>
                Cart
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-print"></span>
                Reports
              </a></li>
            </ul>
          
        </div><!--/span-->
        
        <div class="col-sm-9 col-md-10 main">
          <!--toggle sidebar button-->
          
            <header>
              <h4 class="page_title">Dashboard</h4>
            </header>
         <?php if($user->hasPermission('admin')){?>   
            <div class="content-inner">
              <div class="form-wrapper">
                <div class="row">
                  <h5> <a class="btn" href="admin.php?type=user">User privileges</a></h5>
            <?php if(isset($_GET['type']) && !empty($_GET['type'])){?>
                  <table class="table table-bordered">
                      <thead>
                          <tr>
                              <th>Name</th>
                              <th>Email Address</th>
                              <th>Mobile Number</th>
                              <th>Status</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody>
      <?php $list = DB::getInstance()->query("SELECT * FROM users");
            if(!$list->count()){
                echo 'There is no user to Activate or diactivate';
            }else{
                foreach ($list->results() as $name){?>
                      <?php
                        if($name->user_approved == '1'){
                            $state = "active";
                        }else{
                          $state = "success";
                        }
                      ?>
                      
                      <tr class="<?php echo $state;?>">
                        <?php if(!$name->is_admin == '1'){?>
                        <td><?php echo $name->username ?></td>
                        <td><?php echo $name->email ?></td>
                        <td><?php echo $name->phone ?></td>
                        <td><?php
                          if($name->user_approved == '1'){        
                              echo "<a class='btn btn-sm' href='activated_or_die.php?u_id=$name->id&type=$name->user_approved'>activate</a>";
                          }else{
                              echo "<a class='btn btn-sm' href='activated_or_die.php?u_id=$name->id&type=$name->user_approved'>Deactivate</a>";
                          }
                          echo '</td>
<td>
    <button href="#" data-toggle="modal" class="btn btn-green btn-sm" data-target="#edit'.$name->id.'" ><i class="fa fa-edit fa-1x"></i></button>
    <button href="#" data-toggle="modal" class="btn btn-red btn-sm" data-target="#delete'.$name->id.'" ><i class="fa fa-remove fa-1x"></i></button>
</td>';} 
                          ?>

                        </td>
                      </tr>
                     <?php 
                       }
                     }
                   ?>
                      </tbody>
                  </table>
            <?php }?>
                </div>
                <br>
            </div>
          </div>
      <?php }?>

<?php if(!empty($list)){foreach ($list->results() as $name){ ?>
    <div class="modal fade" id="edit<?php echo $name->id; ?>" tabindex="-1" role="dialog" aria-labelledby="jobModalLabel<?php echo $name->id; ?>" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h5 id="myModalLabel"><i class="fa fa-edit"></i>  Edit User Details</h5>
                </div>
                  <div class="modal-body">
                    <?php
                    if(Input::exists()){
                      if(Token::check(Input::get('token'))){
                          $validation = new Validation();

                          $validation = $validation->check($_POST, array(
                              'name'  => array(
                                  'required' => true,
                                  'min'      => 2,
                                  'max'      => 50
                              )
                          ));

                          if($validation->passed()){
                              try{
                                  $user->update(array(
                                      'username'  => Input::get('username'),
                                      'email'     => Input::get('email'),
                                      'name'      => Input::get('name'),
                                      'phone'     => Input::get('phone')
                                  ) , $name->id);

                                  Session::flash('success', 'Information Updated Successfully');
                                  Redirect::to('admin.php');

                              }catch (Exception $e){
                                  die($e->getMessage());
                              }
                          }else{
                              pre($validation->errors());
                          }
                      }
                  }

                    ?>
                  <form action="" method="post">
                    <div class="form-group">
                        <label for="Text">Username</label>
                        <input type="text" class="form-control" name="username" id="inputEmail" placeholder="Username" value="<?php echo $name->username ?>">
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Name</label>
                        <input type="text" class="form-control" name="name" id="Name" placeholder="Full Name" value="<?php echo $name->name ?>">
                    </div>
                    <div class="form-group">
                        <label for="inputEmail">Email</label>
                        <input type="email" class="form-control" name="email" id="inputEmail" placeholder="Email" value="<?php echo $name->email ?>">
                    </div>
                    <div class="form-group">
                        <label for="inputMobile">Mobile No</label>
                        <input type="Mobile" class="form-control" name="phone" id="inputMobile" placeholder="Mobile No" value="<?php echo $name->phone ?>">
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Add</button>
                      <input type="hidden" name="token" value="<?php echo Token::generate();?>"/>
                      <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
<?php } ?>

<?php foreach ($list->results() as $name){ ?>
    <div class="modal fade" id="delete<?php echo $name->id; ?>" tabindex="-1" role="dialog" aria-labelledby="jobModalLabel<?php echo $name->id; ?>" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-body">
                <p class="red">ARE YOU SURE YOU WANT TO DELETE THIS USER?</p>
                <h5><?php echo $name->name?></h5>
              </div>
              <div class="modal-footer">
                <input class="btn " type=button onClick="parent.location='delete.php?u_id=<?php echo $name->id?>'" value='Yes'>
                <button type="button" class="btn " data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    </div>
<?php }} ?>

<style type="text/css">
.btn-green{
  background-color: #1abc9c;
}
.red {
  color: #e74c3c;
}

.btn-red{
  background-color: #e74c3c;
}
</style>
        <!-- Trigger the modal with a button -->
      </div><!--/row-->
	</div>
</div><!--/.container-->

<div class="footer">
  <div class="container">
            <div class="row">
                <div class="pull-right">
                    <div class="copyright">
                        <p>&copy; 2015 4it All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">Thusitha Thiyushan</a></p>
                    </div>
                </div>
            </div>
        </div>
</div>

    <!--scripts loaded here-->
    
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    
    <script src="js/scripts.js"></script>
  </body>
</html>
<?php
}else{
  Redirect::to('404.php');
}
?>