<?php
require_once 'core/init.php';

if(Session::exists('success')){
    echo Session::flash('success');
}

$user = new User();
if($user->isLoggedIn()){
?>

<html>
  <head>
    <meta charset="utf-8">
    <title>Agri world</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">
	
	  <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link href="css/font-awesome.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="css/styles.css" />
  </head>
  <body >
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <style type="text/css">
   .navbar-brand>img {
   max-height: 100%;
   height: 100%;
   width: auto;
   margin: 0 auto;
   /* probably not needed anymore, but doesn't hurt */
   -o-object-fit: contain;
   object-fit: contain; 
   }
	</style>
	
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container-fluid">
          <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
             <span class="sr-only">navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="index.php"><img src="logo.png" alt="Dispute Bills"></a>
          </div>
          <div class="navbar-collapse">
             <ul class="nav navbar-nav navbar-right">
                <?php if(!$user->isLoggedIn()){?>
                <li>
                   <p class="navbar-text">Already have an account?</p>
                </li>
                <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
                   <ul id="login-dp" class="dropdown-menu">
                      <li>
                         <div class="row">
                            <div class="col-md-12">
                               Login via
                               <div class="social-buttons">
                                  <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                                  <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                               </div>
                               or
                               <form class="form" role="form" action="" method="post" accept-charset="UTF-8" id="login-nav">
                                  <div class="form-group">
                                     <label class="sr-only" for="exampleInputEmail2">Email address</label>
                                     <input type="text" class="form-control" name="username" autocomplete="" id="exampleInputEmail2" placeholder="Email address" required>
                                  </div>
                                  <div class="form-group">
                                     <label class="sr-only" for="exampleInputPassword2">Password</label>
                                     <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required autocomplete="">
                                     <div class="help-block text-right"><a href="">Forget the password ?</a></div>
                                  </div>
                                  <div class="form-group">
                                     <input type="submit" class="btn btn-primary btn-block"value="Sign in"/>
                                  </div>
                                  <div class="checkbox">
                                     <label for="remember"><input type="checkbox" name="remember" id="remember"/> keep me logged-in</label>
                                     <input type="hidden" name="token" value="<?php echo Token::generate();?>"/>
                                  </div>
                               </form>
                            </div>
                            <div class="bottom text-center">
                               New here ? <a href="#"><b>Join Us</b></a>
                            </div>
                         </div>
                      </li>
                   </ul>
                </li>
                <?php }else{?>
                <li class="dropdown">
                   <a href="profile.php?user=<?php echo escape($user->data()->username);?>" class="dropdown-toggle" data-toggle="dropdown">Hello! <b><?php echo escape($user->data()->username);?></b> <span class="caret"></span></a>
                   <ul id="login-dp" class="dropdown-menu">
                      <li>
                         <div class="row">
                            <div class="col-md-12">
                               Settings
                               <div class="form-group">
                                  <a href="#" class="btn btn-fb">Edit Profile</a>
                               </div>
                               <div class="form-group">
                                  <a href="logout.php" class="btn btn-tw"><i class="fa fa-sign-out"></i> Logout</a>
                               </div>
                            </div>
                            <div class="bottom text-center">
                               More Upgade <a href="#"><b>Join Our Commiunity</b></a>
                            </div>
                         </div>
                      </li>
                   </ul>
             </ul>
             <ul class="nav navbar-nav navbar-right">
                <?php if($user->hasPermission('admin')){?>
                <li><a href="admin.php">Dashboad</a></li>
                <?php }}?>
                <li><a href="index.php">Home</a></li>
                <li><a href="neworder.php"><span class="glyphicon glyphicon-shopping-cart"></span>  Cart</a></li>
                <li><a href="#">About Us</a></li>
             </ul>
             <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
             </form>
          </div>
       </div>
    </nav>

    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    
    <script src="js/scripts.js"></script>

    <p>Order Table...  </p>
    
<?php

//connect and insert data to the db using mysqli//
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "agri";

// Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);
// Check connection
if (!$conn) {
    die("Connection failed:<br> " . mysqli_connect_error());
}
else {
  //echo ("successfully connected<br>");
}
if(isset($_POST['delete'])) {
  $id = $_POST['oid'];
  
  $sql = "DELETE FROM order_table WHERE id =".$id."";
    $conn->query($sql);
}
//display reservations details in a table//

// Select all data , display them in a table//
$select = "SELECT * FROM cart";
$result = mysqli_query($conn, $select);


  echo ("<table>
    <tr>
      <th>id</th>
      <th>product_id</th>
      <th>p_name</th>
      <th>cost</th>
      <th>username</th>
          
            
    </tr>");
  if (mysqli_num_rows($result) > 0) { 
    // output data from row by row
    while($row = mysqli_fetch_assoc($result)) {
        //echo "Name: " . $row["name"]. " " . "Age: " . $row["age"]. "<br>";
    echo (
    "<tr>
      <form method=\"post\" action=\"\">
      <td>" . $row["id"] . "</td>
      <td>" . $row["product_id"] . "</td>
      <td>" . $row["p_name"] . "</td>
      <td>" . $row["cost"] . "</td>
      <td>" . $row["username"] . "</td>
      
      
              
              <input name=\"oid\" type=\"hidden\" id=\"oid\" value=\"".$row["id"]."\"\>
              <input class=\"delete1\" name=\"delete\" type=\"submit\" id=\"delete\" value=\"Delete\">
            </td>
          </form>
      
    </tr>");
    }
echo ("</table>");
} 

else {
    /*echo "0 results";*/
}

mysqli_close($conn);

?>


<?php }else{
  Redirect::to('index.php');
}?>
    <!--scripts loaded here-->
    

  </body>
</html>

