<?php
require_once 'core/init.php';

if(Session::exists('success')){
    echo Session::flash('success');
}

$user = new User();
if($user->isLoggedIn()){
?>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Agri world</title>
    <meta name="description" content="This was generated by the Codeply editor and responsive design playground." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Codeply">



    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link href="css/font-awesome.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="css/styles.css" />
  </head>
  <body >
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <style type="text/css">
   .navbar-brand>img {
   max-height: 100%;
   height: 100%;
   width: auto;
   margin: 0 auto;
   /* probably not needed anymore, but doesn't hurt */
   -o-object-fit: contain;
   object-fit: contain; 
   }
</style>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
       <div class="container-fluid">
          <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
             <span class="sr-only">navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="index.php"><img src="logo.png" alt="Dispute Bills"></a>
          </div>
          <div class="navbar-collapse">
             <ul class="nav navbar-nav navbar-right">
                <?php if(!$user->isLoggedIn()){?>
                <li>
                   <p class="navbar-text">Already have an account?</p>
                </li>
                <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
                   <ul id="login-dp" class="dropdown-menu">
                      <li>
                         <div class="row">
                            <div class="col-md-12">
                               Login via
                               <div class="social-buttons">
                                  <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                                  <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                               </div>
                               or
                               <form class="form" role="form" action="" method="post" accept-charset="UTF-8" id="login-nav">
                                  <div class="form-group">
                                     <label class="sr-only" for="exampleInputEmail2">Email address</label>
                                     <input type="text" class="form-control" name="username" autocomplete="" id="exampleInputEmail2" placeholder="Email address" required>
                                  </div>
                                  <div class="form-group">
                                     <label class="sr-only" for="exampleInputPassword2">Password</label>
                                     <input type="password" name="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required autocomplete="">
                                     <div class="help-block text-right"><a href="">Forget the password ?</a></div>
                                  </div>
                                  <div class="form-group">
                                     <input type="submit" class="btn btn-primary btn-block"value="Sign in"/>
                                  </div>
                                  <div class="checkbox">
                                     <label for="remember"><input type="checkbox" name="remember" id="remember"/> keep me logged-in</label>
                                     <input type="hidden" name="token" value="<?php echo Token::generate();?>"/>
                                  </div>
                               </form>
                            </div>
                            <div class="bottom text-center">
                               New here ? <a href="#"><b>Join Us</b></a>
                            </div>
                         </div>
                      </li>
                   </ul>
                </li>
                <?php }else{?>
                <li class="dropdown">
                   <a href="profile.php?user=<?php echo escape($user->data()->username);?>" class="dropdown-toggle" data-toggle="dropdown">Hello! <b><?php echo escape($user->data()->username);?></b> <span class="caret"></span></a>
                   <ul id="login-dp" class="dropdown-menu">
                      <li>
                         <div class="row">
                            <div class="col-md-12">
                               Settings
                               <div class="form-group">
                                  <a href="#" class="btn btn-fb">Edit Profile</a>
                               </div>
                               <div class="form-group">
                                  <a href="logout.php" class="btn btn-tw"><i class="fa fa-sign-out"></i> Logout</a>
                               </div>
                            </div>
                            <div class="bottom text-center">
                               More Upgade <a href="#"><b>Join Our Commiunity</b></a>
                            </div>
                         </div>
                      </li>
                   </ul>
             </ul>
             <ul class="nav navbar-nav navbar-right">
                <?php if($user->hasPermission('admin')){?>
                <li><a href="admin.php">Dashboad</a></li>
                <?php }}?>
                <li><a href="index.php">Home</a></li>
                <li><a href="order.php"><span class="glyphicon glyphicon-shopping-cart"></span>  Cart</a></li>
                <li><a href="#">About Us</a></li>
             </ul>
             <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
             </form>
          </div>
       </div>
    </nav>

<div class="container-fluid">
      <br>
      <div class="row row-offcanvas row-offcanvas-left">
        
         <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">
           
            <ul id="side-bar" class="nav nav-sidebar">
              <li class="active"><a href="#">
                <span class="glyphicon glyphicon-tasks"></span>
                Overview
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-edit"></span>
                Edits
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-pencil"></span>
                Add New Products
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-shopping-cart"></span>
                Cart
              </a></li>
              <li><a href="#">
                <span class="glyphicon glyphicon-print"></span>
                Reports
              </a></li>
            </ul>
            <ul class="nav nav-sidebar">
              <li><a href="">Nav item again</a></li>
              <li><a href="">One more nav</a></li>
              <li><a href="">Another nav item</a></li>
            </ul>
          
        </div><!--/span-->
        
        <div class="col-sm-9 col-md-10 main">
          <!--toggle sidebar button-->
          <p class="visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
          </p>

          <!-- <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder text-center">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder text-center">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder text-center">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder text-center">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div> -->
            <header>
              <h4 class="page_title">Products</h4>
            </header>
            <div class="content-inner">
              <div class="form-wrapper">
                <form>
                  <div class="row form-group">
                    <label class="sr-only">Title</label>
                    <div class="col-md-3">
                      <span class="">Title 1</span>
                      <input type="text" class="form-control" id="titles" placeholder="Article..1">
                    </div>
                    <div class="col-md-3">
                      <span class="">Title 2</span>
                      <input type="text" class="form-control" id="titles" placeholder="Article..2">
                    </div>
                    <div class="col-md-3">
                      <span class="">Title 3</span>
                      <input type="text" class="form-control" id="titles" placeholder="Article..3">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="checkbox">
                    <label>
                      <input type="checkbox"> Publish
                    </label>
                  </div>
                  </div>
                   <div class="clearfix">
                    <button type="submit" class="btn btn-primary">Publish</button>
                   </div>
                </form>
              </div>

          <div class="form-wrapper">
            <div class="table-responsive">
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Header</th>
                    <th>Header</th>
                    <th>Header</th>
                    <th>Header</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1,001</td>
                    <td>Lorem</td>
                    <td>ipsum</td>
                    <td>dolor</td>
                    <td>sit</td>
                  </tr>
                  <tr>
                    <td>1,002</td>
                    <td>amet</td>
                    <td>consectetur</td>
                    <td>adipiscing</td>
                    <td>elit</td>
                  </tr>
                  <tr>
                    <td>1,003</td>
                    <td>Integer</td>
                    <td>nec</td>
                    <td>odio</td>
                    <td>Praesent</td>
                  </tr>
                  
                </tbody>
              </table>
            </div>
          </div>

            </div>
            
            
      </div><!--/row-->
	</div>
</div><!--/.container-->

<footer>
  <p class="pull-right">Developer Thusitha thiyushan ©2015 4it</p>
</footer>
<?php }else{
  Redirect::to('index.php');
}?>
    <!--scripts loaded here-->
    
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    
    <script src="js/scripts.js"></script>
  </body>
</html>